const data = [
	{
		title: "Countries App",
		shortDescription: "A educational Countries app",
		longDescription:
			"This is an educational web application about countries and their geography. It shows a brief description of all the countries in the world and you can add tourist activities specific to each country.",
		stack: [
			"JavaScript",
			"React",
			"Redux",
			"Styled Components",
			"Node Js",
			"Express",
			"Sequelize",
			"Postgres",
		],
		features: [
			"Searching",
			"Filtering",
			"Pagination",
			"Add tourist activities",
		],
		link: "https://countries-app-2022.vercel.app/",
		img: "https://media.istockphoto.com/photos/multi-ethnic-people-portraits-and-national-flags-picture-id510075292?k=6&m=510075292&s=612x612&w=0&h=OcuwVEPipLvMnQwc0-HbQX5QzB8NjOfBEw7l6LR9w1g=",
		coverPage:
			"https://cdn.decrypt.co/resize/1024/height/512/wp-content/uploads/2022/03/Ukraine-Flag-gID_4.png",
	},
	{
		title: "Mangaka",
		shortDescription: "A indie mangas store for readers",
		longDescription:
			"A complete mangas store where anybody can create and sell his mangas, and live of what they love. You can read mangas, and bought them with MangaCoins (an intern currency that you can change for real money)",
		stack: [
			"JavaScript",
			"React",
			"Redux",
			"React Router",
			"Material UI",
			"NodeJS",
			"TypeScript",
			"Express",
			"Passport.js",
			"Prisma",
			"Postgres",
		],
		features: [
			"Searching",
			"Filtering",
			"Pagination",
			"Create mangas",
			"Buy mangas",
			"Add coments",
			"Buy MangaCoins",
			"Super Admin options to control the mangas content",
			"Read mangas",
			"The option to buy a single manga or the complete colection",
		],
		link: "https://deploy-client-kappa.vercel.app",
		img: "https://img.interempresas.net/fotos/2721187.png",
		coverPage:
			"https://www.japonalternativo.com/wp-content/uploads/2021/12/mejor-dibujante-manga-naruto.jpg",
	},
	{
		title: "Products App",
		shortDescription: "An aplication to create and manage products",
		longDescription:
			"A Full Stack application with Node and React with an Admin section to manage the products of an ecommerce. From this admin section you can work with all CRUD operations.",
		stack: [
			"JavaScript",
			"React",
			"Axios",
			"React Router",
			"Styled-Components",
			"NodeJS",
			"Express",
			"JSON Web Tokens",
			"Sequelize",
			"Postgres",
		],
		features: [
			"Product Detail",
			"Pagination",
			"Create Products and Brands",
			"Delete products and brands",
			"Update products and brands",
			"Get all products",
			"Login",
			"Register",
		],
		link: "https://friendly-khorana-d46c86.netlify.app/",
		img: "https://www.conversific.com/wp-content/uploads/2020/03/ecommerce_1280x717-1024x574.jpg",
		coverPage:
			"https://www.loclweb.com/wp-content/uploads/2018/04/local-business-ecommerce-website.png",
	},
];
export default data;
